### ISSUE TITLE
You cannot drag mobbers to change order

### ISSUE THREAD

**Issue by ethanstrominger** [mobtimeapp/mobtime#229] opened 2022-01-08 12:51 UTC
You could previously change order by  hovering over a mobber, a grab symbol woulld appear and you could drag someone to change their order.

**Comment by tedyoung** [comment] 2022-01-14 19:08
I believe this is a dupe of #217 (and yes, I found this bug, too)

**Comment by ssshake** [comment] 2022-01-18 18:39
This issue also occurs for reordering goals #234

**Closed** 2022-01-20 01:55 UTC
